- README.md
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/RequestParser.java
- src/main/java/webserver/ResponseWriter.java
- src/main/java/webserver/WebServer.java
내가 한 것
---
이번에는 코드 구현보다는 웹 소켓이나 http에 대한 이론적인 부분에 좀 더 집중했다.
* 모든 Request Header 출력하기
* BufferedReader.readLine() 메소드 활용해 라인별로 http header 읽음
* Request Line에서 path 분리하기
* String[] tokens = line.split(" "); 활용해 문자열을 분리
* path에 해당하는 파일 읽어 응답
* Files.readAllBytes 활용함
* RequestParser 클래스 생성
* parseRequestStartLineTarget 메서드를 통해 target file(url) 획득
* ResponseWriter 클래스 생성
* OutputStream을 통해 응답 반환하는 메서드 구현
* 주어진 코드를 읽고 웹 소켓 통신의 전체적인 흐름 파악
내가 배운 것
---
* 강의를 듣고 thread에 있어서 start()함수와 run()함수의 차이에 대해 배움
* 웹 서버와 WAS의 차이에 대해 복습
*  둘을 분리해야 하는 이유에 대해 알게 됨
* HTTP 전반에 대한 내용 복습
고민해야 할 것, 더 해야 할 것
---
주어진 코드를 유지보수 측면에서 더 발전시키기
책임별로 클래스 더 나누기
보다 일반화된 요청 처리 및 응답 클래스 구현
> [신정아] 웹 서버 1단계 - index.html 응답 구현 완료

- README.md
- src/main/java/util/HttpRequestUtils.java
- src/main/java/util/HttpStatus.java
- src/main/java/webserver/RequestHandler.java
- src/test/java/HttpRequestUtilsTest.java
Request Line  parsing 및 해당하는 파일을 읽어 http response 하는 기능
회원가입 사용자 Request parsing 및 User 클래스에 저장
HttpRequestUtils util 클래스 생성 및 getUrl함수로 리팩토링
파일 Path 상수 선언
parseQueryString 메소드 구현으로 회원가입 정보(사용자 Request)를 String으로 parsing (split 함수 사용)
나중을 위한 HttpStatus Enum 클래스 추가
util 클래스의 함수 단위 테스트
parseQueryString 메소드를 for문과 split() 메소드로 구현했는데 Arrays.stream()으로 구현 도전
HttpRequest 클래스와 HttpResponse 클래스를 따로 빼서 리팩토링 도전
웹 서버 3단계 구현 도전
구현 함수 마다 단위테스트 도전
> [최주형] 6일차 - 웹 서버 1, 2단계 구현 완료

- README.md
- src/main/java/http/Method.java
- src/main/java/http/RequestLine.java
- src/main/java/http/Uri.java
- src/main/java/webserver/RequestHandler.java
- src/test/java/RequestLineTest.java
- HTTP 메소드, URI, HTTP 버전을 저장해줄 RequestLine 클래스 추가
- URI 클래스 추가
- 주소와 쿼리 파라미터 분리
- RequestLineTest 추가
- step2 기능 추가에 앞선 하드코딩으로 Get으로 회원가입 기능 구현
> [김태완 step1] index.html 응답 기능 구현

- README.md
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
구현 사항
- localhost:8080/index.html로 들어갈 시 프로젝트 내의 정적 index.html파일이 브라우저에 나타나도록 구현.
- 인풋스트림에서 경로명 얻어오기
- 얻어온 경로명을 바탕으로 content type 유추
- 얻어온 경로명을 실제 파일이 위치하고 있는 정적경로명으로 바꿈
- 정적 경로명과 content type을 바탕으로 원하는 화면이 브라우저에 나타나도록 구현
> [한상훈] step1 index.html 응답 구현

- src/main/java/utility/HttpRequestParser.java
- src/main/java/utility/HttpRequestUtils.java
- src/main/java/utility/HttpStatusCode.java
- src/main/java/webserver/RequestHandler.java
- src/test/java/HttpRequestParserTest.java
- src/test/java/HttpRequestUtilsTest.java
- src/test/java/HttpStatusCodeTest.java
* 정적 리소스(index.html) Response로 반환
* 정적 리소스(*.html, *.js, *.css) 의 Response 헤더에 `Content-Type` 추가
* 사용자의 요청을 처리하는 `RequestHandler` 클래스의 기능 중, Request URI로부터 정적 자원 식별, 서빙 하는 기능 분리 - `HttpRequestParser` 클래스
* QueryString 파싱 기능을 가지는 메서드 - `HttpRequestUtil::parseQueryString`추가
* Socket의 `InputStream`을 받아 Request 헤더 파싱, URI 파싱 통해 정적 리소스 반환
> [공윤재] Step1

- README.md
- src/main/java/db/Database.java
- src/main/java/model/domain/User.java
- src/main/java/model/general/Method.java
- src/main/java/model/request/RequestLine.java
- src/main/java/util/HttpRequestUtil.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
HTTP Method 관리하기 위한 enum class 구현
요청 HTTP Message의 첫 번째 줄인 request line을 관리하기 위한 class 구현
학습 내용 기록
> [박준수] 2주차 - step 1 구현

- src/main/java/http/HttpRequest.java
- src/main/java/http/HttpResponse.java
- src/main/java/http/QueryParameters.java
- src/main/java/http/RequestHeader.java
- src/main/java/http/RequestLine.java
- src/main/java/http/Uri.java
- src/main/java/model/User.java
- src/main/java/webserver/Controller.java
- src/main/java/webserver/ControllerHandler.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/UserController.java
- src/main/java/webserver/ViewController.java
- src/test/java/HttpRequestTest.java
- src/test/java/RequestLineTest.java
- GET으로 회원가입 기능 구현
1. Controller 판별 방법 생각해보기
2. Resource 확장자 ENUM 만들기
3. 단위 테스트 진행하기
> [김태완 step2] 2단계 기능 구현

- README.md
- src/main/java/util/HttpRequest.java
- src/main/java/util/HttpRequestParser.java
- src/main/java/webserver/RequestHandler.java
- src/test/java/util/HttpRequestParserTest.java
- HttpRequest 클래스를 통해 request의 헤더와 정보들을 저장
- HttpRequestParser 클래스를 통해 request 파싱하기
ex) mappingPath()
- HttpRequestParserTest 작성
- 기본 구현 후 리팩토링 
- step2 구현 및 리팩토링
> [김지언] Step1 제출합니다.

- src/main/java/http/HttpRequest.java
- src/main/java/http/HttpRequestBody.java
- src/main/java/http/HttpRequestHeader.java
- src/main/java/http/HttpStartLine.java
- src/main/java/utils/FileIoUtils.java
- src/main/java/utils/HttpMethod.java
- src/main/java/utils/HttpRequestGenerator.java
- src/main/java/webserver/RequestHandler.java
- Http 메세지를 기능 단위로 나눠서 클래스로 구현
- FileIoUtil 클래스를 이용하여 기능요구사항인 정적 html 파일 응답 기능을 구현
- HttpMethod Enum Class를 이용하여 각 메서드가 메세지 바디를 가지는지 알 수 있게 구현
- 테스트코드 작성
- 예외 처리 보강, 리팩토링
- step2 기능구현
> [장민호] step1 제출합니다.

- README.md
- src/main/java/controller/Controller.java
- src/main/java/controller/ControllerSelector.java
- src/main/java/controller/TemplateController.java
- src/main/java/request/Request.java
- src/main/java/request/RequestHeader.java
- src/main/java/request/RequestLine.java
- src/main/java/request/RequestURL.java
- src/main/java/response/Response.java
- src/main/java/utils/RequestUtils.java
- src/main/java/webserver/RequestHandler.java
1단계의 경우 간단하게 index 의 경로만 파싱해서 설정해 주면 되는 단계라 손쉽게 진행한 것 같습니다.
이후 단계들을 위해 객체분리하는 부분을 신경써서 구현했습니다.
> [유준민 서버 1단계 구현]

- .github/workflows/pr-merge.yml
- 기존의 자동 머지 스크립트를 수동으로 머지하도록 변경해봤다
- 아직 테스트는 못 해 봄 ㅎㅎ
> 머지 워크플로우 추가

- src/main/java/model/User.java
- src/main/java/utility/HttpRequestParser.java
- src/main/java/utility/HttpRequestUtils.java
- src/main/java/webserver/RequestController.java
- src/main/java/webserver/RequestHandler.java
- src/test/java/HttpRequestParserTest.java
- src/test/java/RequestControllerTest.java
* `/user/create?...` url로 들어오는 회원가입 요청 처리, `User` 생성, Database에 추가
* 요청을 정적 자원, 동적 요청에 따라 처리할 클래스 작성 - `RequestController`
* `User` 클래스에 Builder 패턴 적용
* request header의 파싱 -> `HttpRequestUtils` 클래스로 분리
* `HttpRequestParser`, `HttpRequestUtils`, `RequestController` 클래스의 테스트 추가
* 회원가입 처리 후 /index.html 페이지로 리다이렉트
정적 리소스 반환, 비즈니스 로직 처리 모두 `RequestHandler 의 run()` 메서드가 담당하면 책임이 너무 커져
`RequestController` 클래스의 `staticRequestHandler`, `dynamicRequestHandler` 메서드로 각각 정적 리소스 반환, 비즈니스 로직 처리 역할을 나눔
3xx 코드와 Location 헤더로 리다이렉트 수행
> [공윤재] - Step2, 회원가입 기능 구현

- README.md
- src/main/java/Controller/Controller.java
- src/main/java/Controller/UserController.java
- src/main/java/http/HttpHeader.java
- src/main/java/http/HttpRequest.java
- src/main/java/http/HttpRequestLine.java
- src/main/java/http/HttpResponse.java
- src/main/java/http/HttpStatus.java
- src/main/java/http/HttpUri.java
- src/main/java/util/HttpRequestUtils.java
- src/main/java/webserver/ControllerHandler.java
- src/main/java/webserver/RequestHandler.java
無
클래스, 인터페이스 추가
+ http 관련
+ HttpHeader, HttpRequest, HttpRequestLine, HttpResponse, HttpStatus, HttpUri
+ Controller
+ Controller(interface), UserController
+ Handler
+ ControllerHandler
클래스, 인터페이스 추가 후 리팩토링을 진행하였다.
RequestHandler에서 HttpRequest를 확인 하고 ControllerHandler로 user 관련 요청인지 확인한다.
user 관련 요청일 경우 UserController에서 user가 어떤 요청을 했는지 확인하고 
요청에 맞는 응답을 HttpResponse에 넣어 주는 과정으로 설계할 예정이다.
못한 리팩토링 마저 하기 - HttpResponse
웹 서버 3단계 구현 도전
구현 함수 마다 단위테스트 도전
> [최주형] 7일차 - REFACTOR

- README.md
- src/main/java/reader/RequestGetReader.java
- src/main/java/reader/RequestReader.java
- src/main/java/reader/fileReader/FileReader.java
- src/main/java/reader/fileReader/StaticFileReader.java
- src/main/java/reader/fileReader/TemplatesFileReader.java
- src/main/java/request/HttpRequest.java
- src/main/java/response/HttpResponse.java
- src/main/java/util/FileType.java
- src/main/java/util/HttpMethod.java
- src/main/java/util/HttpStatus.java
- src/main/java/util/Url.java
- src/main/java/util/UrlType.java
- src/main/java/webserver/RequestHandler.java
- src/main/resources/templates/index.html
- src/main/resources/templates/user/form.html
- src/test/java/reader/RequestGetReaderTest.java
- src/test/java/reader/RequestReaderTest.java
- src/test/java/reader/fileReader/FileReaderTest.java
- src/test/java/reader/fileReader/TemplatesFileReaderTest.java
- src/test/java/util/FileTypeTest.java
- src/test/java/util/HttpMethodTest.java
- src/test/java/util/UrlTypeTest.java
- user/form.html 링크 접속시 html response
- css/js/font등 적용( 하다보니 Step3도 조금 하게 되었습니다.)
- 회원가입 등록하기 버튼 클릭시 서버에게 QueryString 형식으로 데이터 전달
- client가 보낸 회원데이터 저장(User,Database 미사용)
- 왜 스프링을 사용하는지 알 거 같습니다....
- Http를 직접 구현하는데 어디까지 객체분리를 하여야 하는건지 헷갈립니다.
- stylesheet를 적용해야할때 객체 분리가 잘되어있어서 추가만 하고 수정을 거의 없이 적용을 했던것이 인상깊었습니다!
> [김규민] Step-2  - GET으로 회원가입

- README.md
- src/main/java/controller/ControllerSelector.java
- src/main/java/controller/StaticController.java
- src/main/java/controller/UserController.java
- src/main/java/request/Request.java
- src/main/java/request/RequestLine.java
- src/main/java/response/Response.java
Url 파싱을 하는 부분에서, static인지, user 관련인지, Template 인지 구분하여 리퀘스트를 관리 할 수 있도록 컨트롤러를 만들었습니다. 
response 의 부분에도 리디렉션을 위해 302와 css 일 경우 response header를 따로 설정해 주었습니다.
처음 해보는 부분이라 실수가 많았는데, 동기들의 도움을 많이 받아 잘 해결한 듯 싶습니다.
내일부터는 리펙토링을 해 보려고 합니다.
> [유준민 서버 Step2,3 구현]

- src/main/java/controller/SignUpController.java
- src/main/java/utils/FileIoUtils.java
- src/main/java/utils/HttpRequestUtils.java
- src/main/java/utils/Utilites.java
- src/main/java/webserver/ContentType.java
- src/main/java/webserver/HttpMethod.java
- src/main/java/webserver/HttpRequest.java
- src/main/java/webserver/HttpResponse.java
- src/main/java/webserver/HttpStatus.java
- src/main/java/webserver/RequestDispatcher.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/RequestParser.java
- src/main/java/webserver/RequestStartLine.java
- src/main/java/webserver/ResponseWriter.java
- src/main/java/webserver/WebServer.java
- src/test/java/RequestParserTest.java
- src/test/java/RequestStartLineTest.java
내가 한 것
---
* 쿼리 파라미터를 읽어와서 파싱하여 map에 저장함
* 해당 map의 정보를 바탕으로 새로운 User를 생성함
* HttpRequest, HttpResponse 객체를 생성하여 보다 일반적인 요청에 대한 처리가 가능하도록 함
* Utils를 통해 일반적인 파일 읽어 오기가 가능하도록 함
* 파일이 없을 경우의 예외처리를 해줌
* RequestStartLine을 통해 requestStartLine 정보를 처리할 수 있도록 함
* HttpMethod, HttpStatus들을 enum으로 선언하여 관리할 수 있도록 함
* ResponseWriter를 통해 보다 일반적인 응답을 내릴 수 있도록 리팩토링
* 회원가입 진행 후 HttpResponse의 헤더에 Location 속성을 추가하여 로그인 페이지로 리다이렉션 해주기
내가 배운 것
---
* 쿼리 파라미터에 대해 좀 더 자세히 알 수 있었음
* HttpRequest 객체에 대한 처리 과정을 통해 Request Message 구조에 대해 파악함
* HttpResponse를 통해 직접 응답을 내려주면서 Http Response 생성 과정에 대해 파악하였음
더 고민해야 할 것, 해야 할 것
---
* 현재 회원 가입을 요청했을 때 컨트롤러가 너무 세분화(?) 되어 있음
* 요청에 대한 처리를 담당하는 부분를 좀 더 추상화시켜야 할 필요가 있음
* 요청에 따라 적절한 컨트롤러를 반환하는 클래스 생성
* 컨트롤러에 몰려있는 로직 처리 부분을 service 패키지로 분리해야 할 듯
> [신정아] 웹 서버 2단계 - GET으로 회원가입 구현 완료

- src/main/java/db/Database.java
- src/main/java/db/MemoryDatabase.java
- src/main/java/http/HttpRequest.java
- src/main/java/http/repsonse/HttpResponse.java
- src/main/java/http/request/HttpRequest.java
- src/main/java/http/request/HttpRequestBody.java
- src/main/java/http/request/HttpRequestHeader.java
- src/main/java/http/request/HttpStartLine.java
- src/main/java/service/UserService.java
- src/main/java/service/UserServiceImpl.java
- src/main/java/utils/FileIoUtils.java
- src/main/java/utils/HttpMethod.java
- src/main/java/utils/HttpRequestGenerator.java
- src/main/java/utils/HttpResponseGenerator.java
- src/main/java/utils/HttpUtils.java
- src/main/java/utils/StatusCode.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
- src/test/java/ParseQueryTest.java
- Step2 회원가입기능 구현
- Databse를 인터페이스와 구현체를 분리하여 UserService와 결합도를 낮춤.
- Status code를 Enum을 이용하여 구현함
- 적절한 Content-Type을 반환하는 메서드 구현
- HttpResponse 클래스 구현
- 오늘 구현한 클래스들 유닛 테스트
- 작성한 코드들 리팩토링
> [장민호] Step2 구현

- src/main/java/controller/Controller.java
- src/main/java/controller/HomeController.java
- src/main/java/controller/NotFoundController.java
- src/main/java/model/general/Header.java
- src/main/java/model/general/Status.java
- src/main/java/model/request/RequestLine.java
- src/main/java/model/response/Response.java
- src/main/java/model/response/StatusLine.java
- src/main/java/util/ControllerMapper.java
- src/main/java/webserver/RequestHandler.java
RequestHandler에서 요청 HTTP message의 request line 읽어 와서 파싱하고 경로에 있는 index.html 및 응답 헤더 정보를 OutputStream에 write하는 것까지 모두 처리
1. RequestHandler에서 요청 HTTP message의 request line 읽어 온다.
2. ControllerMapper에게 request line 정보 보내서 올바른 Controller를 받아 온다.
3. 해당하는 특정 Controller에서 추가적인 처리를 거친 후, Response를 리턴한다.
4. 받아온 Response 객체를 토대로 OutputStream에 write한다.
1. DataOutputStream에 write하는 로직 분리할 수 있을 것 같아서 함수 분리
2. getResponse는 Response를 리턴하는 역할만 해야 할 것 같아서 로직은 따로 함수를 두고 구현한 후, getResponse는 Response 객체를 리턴하는 역할만 하도록 구현
3. 아무 정보도 요청하지 않거나 잘못된 요청을 보내는 경우를 아직 면밀하게 확인하지 않아서 추가 확인
4. 2단계 구현⭐️⭐️⭐️
- Controller: Interface
- HomeController: index.html 입력 받았을 때 처리 담당
- NotFoundController: 아무 것도 입력 받지 않았거나 잘못된 입력을 받았을 경우 처리 담당
- Header: 헤더 정보를 담고 있는 enum 객체
- Status: 응답 상태 코드와 메시지를 담고 있는 enum 객체
- StatusLine: 응답 HTTP …
> [박준수] 2주차 미션 기존 구조 변경 후 1단계까지 적용

- src/main/java/controller/UserController.java
- src/main/java/model/User.java
- src/main/java/webserver/HttpRequest.java
- src/main/java/webserver/HttpRequestUtils.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/RequestUtils.java
- src/main/java/webserver/ResponseWriter.java
- src/main/java/webserver/Url.java
- src/main/java/webserver/WebServer.java
- HttpRequestUtils 클래스 구현 (inputStream으로부터 파싱하여 HttpRequest 객체 생성, queryString 파싱)
- user 관련 API를 처리할 UserController  클래스 구현
- Response 작성을 담당하는 ResponseWriter 클래스 구현
- method와 contentType을 enum으로 리팩토링하기
- controller 추상화시키기
- controller로 요청을 전달하는 RequestMappingHandler를 구현하기
- ViewResolver 구현하기
> [유경민] Step2 구현 완료

- README.md
- src/main/java/model/User.java
- src/main/java/service/UserService.java
- src/main/java/util/FileFinder.java
- src/main/java/util/HttpParser.java
- src/main/java/webserver/HttpRequest.java
- src/main/java/webserver/HttpResponse.java
- src/main/java/webserver/RequestHandler.java
- src/test/java/util/HttpParserTest.java
- Step 1 에서 HttpRequest, HttpResponse 를 사용하도록 리팩토링
- Database 접근을 위해 UserService 클래스 정의
- FileFinder 클래스가 해당 경로의 파일을 찾도록 위임
- body 데이터에 맞는 MIME 타입을 Content-Type으로 주도록 구현
- 금일 학습 내용 정리
- Request에 관련된 것들을 Map으로 이용하는 것은 어떤 Request의 정보인지 식별하기 쉽지않다고 판단, 각 요청마다 HttpRequest를 만들고 그 객체가 Header의 정보를 관리하도록 수정
- 데이터베이스에 접근하는 로직은 짧은 트랜잭션에서 관리되어야한다고 생각되었다. 따라서 User를 생성해 addUser()하는 db 접근작업만 처리하도록 수정
- 지정된 경로의 파일을 찾아 byte[] 로 변환하는 작업은 주기적으로 일어날 것으로 보여서, 따로 클래스로 관리하도록 수정
- content-type을 명시하지 않으면 브라우저는 text 데이터로 인식하고 기존의 코드는 text/html로 하드코딩 되어있어서 css, js, fonts 파일등을 얻어올 때 경로를 명시해도 가져오지 못한는 경우가 있었음. 이를 해결하기 위해 body 타입에 맞는 MIME 타입을 반환하도록 구현하였다.
> [Step2] 박원종 step2 제출합니다.

- README.md
- src/main/java/model/User.java
- src/main/java/request/HttpMethod.java
- src/main/java/request/Request.java
- src/main/java/request/RequestHandler.java
- src/main/java/request/RequestHandlerImpl.java
- src/main/java/request/RequestParser.java
- src/main/java/request/ResponseGenerator.java
- src/main/java/request/ResponseGeneratorImpl.java
- src/main/java/request/methodHandler/DELETEHandlerImpl.java
- src/main/java/request/methodHandler/GETHandlerImpl.java
- src/main/java/request/methodHandler/HttpMethodHandler.java
- src/main/java/request/methodHandler/POSTHandlerImpl.java
- src/main/java/request/methodHandler/PUTHandlerImpl.java
- src/main/java/response/HttpResponse.java
- src/main/java/webserver/ClientRequestThread.java
- src/main/java/webserver/WebServer.java
* STEP2 구현
* enum을 이용해 if문 없이 GET,POST 등 요청 메소드가 분기되도록 리팩토링
* html 파일이 렌더링 되는 과정 및 서버의 응답에 따른 브라우저의 동작 학습
* 요청에 따른 응답 반환 구현 및 예외처리
* 자바 공부
> [장덕진] STEP2 구현 완료

- .github/workflows/pr-merge.yml
불필요한 on: schedule 을 주석 처리하니 정상 동작함
> 머지 액션 오류 수정

- src/main/java/controller/Controller.java
- src/main/java/controller/ControllerFactory.java
- src/main/java/controller/IndexController.java
- src/main/java/controller/ResourceController.java
- src/main/java/controller/UserCreateController.java
- src/main/java/db/Database.java
- src/main/java/http/ContentType.java
- src/main/java/http/HttpRequest.java
- src/main/java/http/HttpResponse.java
- src/main/java/http/HttpStartLine.java
- src/main/java/http/HttpStatusCode.java
- src/main/java/http/Parameter.java
- src/main/java/http/Uri.java
- src/main/java/service/UserService.java
- src/main/java/utils/FileIoUtils.java
- src/main/java/utils/HttpRequestUtil.java
- src/main/java/webserver/RequestHandler.java
- src/test/java/http/HttpStartLineTest.java
- src/test/java/http/ParameterTest.java
- src/test/java/http/UriTest.java
- src/test/java/service/UserServiceTest.java
- src/test/java/utils/FileIoUtilsTest.java
- src/test/java/utils/HttpRequestUtilTest.java
- HttpRequest 세분화 (클래스 분리)
- 컨트롤러를 핸들링해줄 수 있는 ControllerFacotry 구현
- 회원가입 기능 추가
- 회원가입 후 리다이렉트 또는 회원가입 완료했다는 form 만들기
- Controller 추상클래스를 만들어서 중복된 코드 줄이기
- 단위 테스트 구현 및 리팩토링 필요
- 404 예외처리 생각하기
> [김강산] Step2 - 회원가입 기능 구현

- src/main/java/controller/Controller.java
- src/main/java/controller/FrontController.java
- src/main/java/controller/SignUpController.java
- src/main/java/model/User.java
- src/main/java/utils/GeneralUtils.java
- src/main/java/utils/HttpRequestUtils.java
- src/main/java/webserver/HttpResponse.java
- src/main/java/webserver/RequestDispatcher.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/ResponseWriter.java
내가 한 것
---
* 엔티티(유저 객체)에 대해 정적 팩토리 메서드 패턴 적용
* 생성자를 private으로 바꾸고, of함수를 static으로 선언
* 요청에 대해 일반적인 처리가 가능하도록 프론트 컨트롤러 패턴 적용
* 추상화가 추가되면서 세부적인 구현체에 대한 분기문이 없어짐 
* MIME 에 대해 알아보고, 해당 파일의 확장자를 통해 HttpResponse의 content-type을 넣어서 반환해줌
* 피드백에 따라 단순 html 반환인지 아닌지 판단하는 분기문 조건 수정
* url에 따라 static 디렉토리에 대해 경로를 설정할지, templates 디렉토리에 대해 경로를 설정할지 판단하는 분기문 추가
* 피드백에 따라 HttpResponse를 받아오는(?) 로직의 형식 공통화
* 컨트롤러의 리턴값으로 HttpResponse를 받아오게 해서 response 객체가 새롭게 2번이나 생성되었음
* 리턴값이 아니라 파라미터로 넘겨주어 객체를 굳이 또 만들지 않아도 되게 함  
내가 배운 것
---
* MIME 
* 정적 팩토리 메서드 패턴
* 프론트 컨트롤러 패턴
* 메서드의 리턴값으로 객체를 받아오기 vs 파라미터로 객체를 넣어주기
더 고민해야 할 것, 해야 할 것
---
* 좀 더 리팩토링할 지점이 있는지 고민
* 현재 컨트롤러의 로직을 서비스 단으로 분리
* 단위 테스트 구현하기
* BDD 적용
> [신정아] step3 구현 완료

- src/main/java/controller/HomeController.java
- src/main/java/controller/NotFoundController.java
- src/main/java/controller/UserController.java
- src/main/java/db/Database.java
- src/main/java/model/domain/User.java
- src/main/java/model/general/Status.java
- src/main/java/model/request/RequestLine.java
- src/main/java/model/response/Response.java
- src/main/java/model/response/StatusLine.java
- src/main/java/service/UserService.java
- src/main/java/util/ControllerMapper.java
- src/main/java/webserver/RequestHandler.java
1. OutputStream에 response message 쓰는 함수에서 status line, header, body 쓰는 로직 모두 담고 있어서 각각 함수로 추출
2. getResponse 함수에 index.html 응답하는 로직이 담겨 있어서 따로 함수로 빼고, Response 객체만 리턴할 수 있도록 수정
3. 아무 정보도 요청하지 않는 경우 처리해주고, 잘못 요청이 오는 경우 잘 처리되는지 확인
1. /user/create 요청받는 경우, query string parsing할 수 있도록 함수 구현
2. 회원 가입하는 로직 처리하기 위해 UserService 만들고, UserController에 의존성 주입
3. Database 객체 UserService에 의존성 주입
4. 회원 가입 이후, 홈 화면으로 리다이렉트할 수 있도록 구현
1. 절대 경로 -> 상대경로 수정
2. 응답 헤더랑 바디 만드는 로직 중복되는 것 같아서 따로 함수로 추출할 수 있을지 고려
3. 정적 파일 요청되는 경우 처리 어떻게 할지 생각
4. 일단 3단계 구현하고 테스트까지 진행할 수 있으면 하기
> [박준수] 2주차 - 1단계 코드 정리 및 2단계 회원 가입 기능 구현 완료

- src/main/java/http/common/HttpHeaders.java
- src/main/java/http/common/HttpStatus.java
- src/main/java/http/exception/BadRequestException.java
- src/main/java/http/exception/HttpException.java
- src/main/java/http/exception/HttpExceptionHandler.java
- src/main/java/http/exception/NotFoundException.java
- src/main/java/http/response/HttpResponse.java
- src/main/java/http/util/HttpHeaderParser.java
- src/main/java/webserver/Dispatcher.java
- src/main/java/webserver/RequestHandler.java
- src/main/resources/templates/not_found.html
1. 코드리뷰 피드백 반영
2. 예외 처리 구현
3. 404 Found 페이지 작성 및 적용
`HttpHeaders` 는 헤더의 단일 추가와 복수 추가 모두 지원
하지만 단일의 경우 `putHeader`, 복수의 경우 `addHeaders`의 이름으로 의미가 통일되지 않음
따라서 `putHeader`메서드 명을 `addHeader`로 수정 및 `addHeaders`의 파리미터를 `Map<String, String>`에서 `HttpHeaders`로 수정
1. `RuntimeException`을 구현한 `HttpException` 추상 클래스 작성
2. `HttpException` 추상 클래스를 상속받는 `NotFoundException` 작성
3. `HttpException` 추상 클래스를 상속받는 `BadRequestException` 작성
4. `HttpException` 에러에 대한 예외 처리를 수행하는 `HttpExceptionHandler` 작성
5. `NotFountException` 에러에 대한 예외 처리를 수행하는 `notFoundExceptionHandler` 메서드를 `HttpExceptionHandler` 에 구현
6. `HttpException` 에러에 대한 기본(공통적인) 예외 처리를 수행하는 `defaultExceptionHandler` 메서드를 `HttpExceptionHandler` 에 구현
404예외 발생 시 클라이언트에 응답할 간단한 페이지 작성
1. 미구현 HttpException 작성 및 핸들러(메서드) 구현하기
2. 예외 처리에 대한 테스트 케이스 작성하기
3. …
> [박솔찬] Day3 피드백 반영 및 예외 처리 구현

- src/main/java/file/FilePostfix.java
- src/main/java/request/HttpMethod.java
- src/main/java/request/Request.java
- src/main/java/request/RequestHandlerImpl.java
- src/main/java/request/methodHandler/GETHandlerImpl.java
- src/main/java/request/methodHandler/RequestUrlEnum/GETRequestUrlEnum.java
- src/main/java/response/HttpResponse.java
- src/main/java/webserver/ClientRequestThread.java
* STEP3 구현 - 클라이언트에서 요구하는 파일의 타입에 맞춰 response의 content type 반환
* request 처리 및 response 생성 시 발생하는 예외에 대한 처리
> [장덕진] STEP3 구현 완료

- src/main/java/controller/ControllerHandler.java
- src/main/java/controller/ControllerNotFoundException.java
- src/main/java/controller/UserController.java
- src/main/java/http/HttpResponse.java
- src/main/java/http/HttpStatus.java
- src/main/java/http/QueryParameters.java
- src/main/java/http/ResourceType.java
- src/main/java/http/ResourceTypeNotFoundException.java
- src/main/java/http/Uri.java
- src/main/java/webserver/RequestHandler.java
- src/test/java/ExceptionTest.java
> [김태완 step3] 예외처리 일부 적용

- README.md
- src/main/java/controller/BaseController.java
- src/main/java/controller/Controller.java
- src/main/java/controller/FrontController.java
- src/main/java/controller/ReturnFileController.java
- src/main/java/controller/SignUpController.java
- src/main/java/service/SignUpService.java
- src/main/java/webserver/ContentType.java
- src/main/java/webserver/HttpStatus.java
- src/main/java/webserver/RequestDispatcher.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
내가 오늘 한 것
---
* 오늘은 피드백 받은 대로 프론트 컨트롤러 패턴에 대해 더 공부하고 어제에 이어 리팩토링함
* 분기 처리 삭제
* RequestHandler에서는 FrontController에게만 모든 요청을 넘겨주면 됨
* 기존에는 RequestHandler에서 요청에 해당되는 컨트롤러를 찾아서 넘김
* 프론트 컨트롤러 내부에서 Map을 통해 각 컨트롤러에 대한 정보를 알고 있음
* 객체 캐싱을 통해 구현
* BaseController를 통해 service(), doGet(), doPost() 구현 - 에러가 발생했을 시를 처리하게 함
* 각 자식 객체는 위의 메서드들을 오버라이딩하여 요청의 http method 에 맞게 로직 수행
내가 배운 것
---
* 스프링의 흐름이 프론트 컨트롤러 패턴임
* 스프링에 사용자의 요청이 왔을 때 어떤 흐름을 통해 응답을 다시 반환하는지 이해함
더 해야 할 것
---
* 테스트 코드 추가 
* 메서드 단위 테스트 
* 예외 처리
> [신정아] 코드 리팩토링 

- README.md
- src/main/java/controller/RequestController.java
- src/main/java/dto/HttpResponse.java
- src/main/java/utility/HttpRequestParser.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
- src/test/java/RequestControllerTest.java
* 파라미터 타입만 다른 중복 메서드 삭제
* 파일의 역할 범주에 따라 관련 패키지 생성, 및 이동
* 무분별한 Thread 생성 오버헤드 줄이기 위해 Socket 연결 생성에 ThreadPool 이용
**파라미터 타입만 다른 중복 메서드 삭제**
String, InputStream 타입 모두 이용하던 의존관계 제거로 InputStream 타입만 이용하도록 변경
**Socket 연결 생성에 ThreadPool 이용**
ThreadPool에 존재하는 Thread 빌려 요청 처리 후 반환
> [공윤재] Step3 리팩토링 & readme 추가

- build.gradle
- src/main/java/request/HttpMethod.java
- src/main/java/request/RequestHandler.java
- src/main/java/request/RequestHandlerImpl.java
- src/main/java/request/methodHandler/DELETEHandlerImpl.java
- src/main/java/request/methodHandler/GETHandlerImpl.java
- src/main/java/request/methodHandler/HttpMethodHandler.java
- src/main/java/request/methodHandler/POSTHandlerImpl.java
- src/main/java/request/methodHandler/PUTHandlerImpl.java
- src/main/java/request/methodHandler/RequestUrlEnum/GETRequestUrlEnum.java
- src/main/java/response/HttpResponse.java
- src/main/java/response/HttpResponseBody.java
- src/main/java/response/HttpResponseHeader.java
- src/main/java/response/HttpResponseStatus.java
- src/main/java/webserver/ClientRequestThread.java
- src/test/java/request/methodHandler/RequestUrlEnum/GETRequestUrlEnumTest.java
* STEP3 코드 리팩토링
* 요청을 처리하는 기능에서 응답도 생성했던 기존 코드에서 응답을 생성하는 기능 분리
* 유효하지 않은 파일 요청이나 존재하지 않는 url로의 get 요청에 대해 404 response 반환 기능 추가
> [장덕진] STEP3 코드 리팩토링

- src/main/java/Controller/ResourceController.java
- src/main/java/Controller/StaticResourceController.java
- src/main/java/Controller/UserController.java
- src/main/java/http/response/HttpResponse.java
- src/main/java/util/ControllerMapper.java
- src/main/java/webserver/RequestHandler.java
코드 구조를 개선하고 리팩토링을 진행하였습니다.
1. 요청에 따라 적절한 컨트롤러를 반환할 때, 정적 파일인 경우 파일 확장자를 검사하여 허용되는 확장자인 경우 `StaticResourceController`를 반환하도록 하고, 매핑할 수 있는 컨트롤러가 없을 경우 예외를 발생하도록 함
- `StaticResourceController`에 `supportedFileExtensions` 정적 멤버 변수를 추가해 허용 가능한 파일 확장자를 저장함
- `StaticResourceController`에 허용 가능한 `URL`인지 판별하는 `isSupported()` 메서드 추가
- `ControllerMapper`에서 `StaticResourceController.isSupported()` 메서드를 호출하여 허용 가능한 `URL`이면 `StatcResourceController`를 반환하도록 함
2. `"/user"`를 `UserController`에 `PREFIX` 상수로 정의하여 관리
- `controllerMapper`의 `key`는 해당 컨트롤러의 `PREFIX`
3. `HttpResponse` 클래스에 응답에 비어있는 바디 메시지를 저장하는 `setEmptyBody()` 메서드 추가
4. `makeBodyMessage()` 메서드 내에서 바디 메시지가 `null`이면 예외를 발생시키도록 함
5. 리다이렉트하는 경우 status line과 header를 추가하는 기능을 `HttpResponse` 클래스에 `redirect()` 메서드를 추가해 수행하도록 함
- `ResourceController` 클래스를 …
> [임수민] 웹 서버 3단계 코드 구조 개선 및 리팩토링

- README.md
- src/main/java/controller/StaticFileController.java
- src/main/java/controller/UserController.java
- src/main/java/http/HttpHeader.java
- src/main/java/http/HttpUri.java
- src/main/java/http/exception/NullHttpRequestException.java
- src/main/java/http/request/HttpRequest.java
- src/main/java/http/request/HttpRequestLine.java
- src/main/java/http/response/HttpResponse.java
- src/main/java/service/LogInService.java
- src/main/java/service/SignUpService.java
- src/main/java/util/HttpRequestUtils.java
- src/main/java/util/HttpResponseUtils.java
- src/main/java/webserver/ControllerHandler.java
- src/main/java/webserver/RequestHandler.java
- src/main/resources/templates/user/form.html
회원 가입 POST request 처리
로그인 기능 구현 중 - 성공 실패만 나누어 놓음
회원가입 기존의 GET 메세지를 POST로 변경 후 관련 함수 수정
httpResponse 객체 생성자에 null 넣다가 저번주 세미나와 피드백때 배운 builder 패턴으로 변경
LogInService 클래스를 추가하여 로그인 성공, 실패 구별
null request가 들어왔을 때 예외처리 - postman 쓰다가 발견
로그인 성공, 실패 이후 로직 구현
postman 더 써보기
5단계 쿠키 세션 구현 도전
> [최주형] 11일차 - 4단계 구현

- src/main/java/controller/Controller.java
- src/main/java/controller/ControllerHandler.java
- src/main/java/controller/UserController.java
- src/main/java/controller/ViewController.java
- src/main/java/http/HttpRequest.java
- src/main/java/http/HttpResponse.java
- src/main/java/http/RequestHeader.java
- src/main/java/http/ResourceType.java
- src/main/java/http/Uri.java
- src/main/java/webserver/RequestHandler.java
- src/main/resources/templates/user/form.html
- src/test/java/ControllerHandlerTest.java
- src/test/java/HttpRequestTest.java
- HTTP POST의 동작방식을 이해하고 이를 이용해 회원가입을 구현할 수 있다.
- HTTP redirection 기능을 이해하고 회원가입 후 페이지 이동에 적용한다.
- HttpMethod에 따른 컨트롤러 핸들러 수정
- 패키지 구조 변경
- 클래스명 이상한거 변경
- 테스트 코드 추가
> [김태완] Step4 기능 구현

- README.md
- src/main/java/controller/Controller.java
- src/main/java/controller/ControllerSelector.java
- src/main/java/controller/StaticController.java
- src/main/java/controller/TemplateController.java
- src/main/java/controller/UserController.java
- src/main/java/enums/MethodEnums.java
- src/main/java/request/Request.java
- src/main/java/request/RequestBody.java
- src/main/java/request/RequestHeader.java
- src/main/java/request/RequestLine.java
- src/main/java/request/RequestURL.java
- src/main/java/response/Response.java
- src/main/java/webserver/RequestResponseHandler.java
- src/main/java/webserver/WebServer.java
- src/main/resources/templates/user/form.html
[ 변경점 ] 
1. get 이던 회원 가입 부분 post 로 변경
2. post 로 변경하기 위해 비어있던 requestbody 구현, 나머지 request 부분 수정
3. Controller 부분 request 의 형태가 바뀜에 따라 약간의 파라미터 수정
4. README 부분 깔끔하게 수정
[ 개선점 ]
1. todo 부분 기능 구현이 끝나면 확인 후 수정
2. postman 에서 null 들어오는 것 확인 후 정상적인 null 값이면 처리
3. Controller select 부분에서 dept 나 경우에 맞게 조금 더 구체적인 수정이 필요.
4. 빌더 패턴 고려해보고 사용해보기.
[ 한마디 ]
PR 이나 README 부분을 조금 더 리뷰어를 위해 작성해 보고 싶어서 이번주 부터 시도 해 봅니다. 작성 방법에 많은 조언을 주신 #rohsik2 님 감사의 말 올립니다.
아직 기능 구현의 부분이 다듬어 지지 않았기 때문에 내일 추가적으로 진행 할 예정입니다.
> [유준민 3주차 서버 4단계] 기능 구현

- src/main/java/controller/FrontController.java
- src/main/java/controller/SignUpController.java
- src/main/java/service/SignUpService.java
- src/main/java/webserver/ContentType.java
- src/main/java/webserver/HttpRequest.java
- src/main/java/webserver/RequestParser.java
- src/main/resources/templates/user/form.html
내가 한 것
---
* 유저회원 가입 폼 메서드 get에서 post로 변경
* 요청에서 header값 파싱해서 저장하는 로직 수정
* line 읽는 것에 대한 while문 조건이 잘못 되어 있어서 header 값들이 빈 값이 되어 있었음
* 오늘 잘못 된 걸 알고 조건문 판단하는 메서드를 따로 빼서 구현함
* readBody()함수를 통해 Http요청 메세지의 본문을 읽어오도록 구현함
* 헤더의 contentLength값만큼 읽어올 수 있도록 BufferedReader의 read함수를 사용해서 구현함
* signUpController에서 doPost() 메서드 오버라이딩
* post 요청에 대해 service 메서드에서 분기를 타고 와서 처리되도록 해줌
* 유저 생성과 유저 저장, redirect에 대한 로직들을 각 메서드들로 분리함
* 단일 책임 원칙에 맞게 로직을 메서드들로 쪼갬
내가 배운 것
---
* http 메세지에서 ContentLength 헤더는 메세지 본문에 대한 크기를 나타냄
* BufferedReader의 read함수는 특정 크기만큼만 읽어냄
* 오늘 내가 한 코딩과는 별개로 reflecton에 대해 공부해봄
해야할 것, 더 배워야 할 것
---
* 더 리팩토링될 여지가 어디에 있는지 고민
* 예외 처리
* 테스트 코드 작성
> [신정아] Step4 구현 완료

- src/main/java/controller/UserController.java
- src/main/java/model/general/Header.java
- src/main/java/model/request/Request.java
- src/main/java/model/request/RequestBody.java
- src/main/java/service/UserService.java
- src/main/java/util/SessionUtils.java
- src/main/resources/templates/user/form.html
POST로 요청이 들어오는 경우를 처리해주기 위해 RequestBody class 구현
이후, Request 객체가 RequestBody 객체를 가질 수 있도록 수정
UserService에서 로그인 함수 구현
로그인에 성공하는 경우와 실패하는 경우의 응답 헤더를 만들어주기 위한 함수 구현(헤더 생성하는 함수 따로 추출할 수 있을지 고민 중)
SessionUtils라는 class 생성 후, 길이를 19로 설정하여 session ID 랜덤하게 생성하는 함수 구현
응답 HTTP 메시지에 Set-Cookie 헤더 잘 담기고, 요청 HTTP 메시지에 해당 정보가 잘 담겨서 넘어올 수 있도록 구현
올바른 class에 올바른 함수가 위치해 있는지, 따로 추출할 수 있는 로직이 있는지 확인
세션 사용해서 로그인 구현 후, 3단계 미션 동적인 HTML까지 구현
README 정리
> [박준수] POST로 회원 가입 구현, 쿠키를 이용한 로그인 구현 중

- src/main/java/controller/LoginController.java
- src/main/java/controller/UserController.java
- src/main/java/controller/UserCreateController.java
- src/main/java/controller/UserLoginController.java
- src/main/java/http/HttpHeader.java
- src/main/java/http/request/HttpRequest.java
- src/main/java/http/request/HttpRequestBody.java
- src/main/java/http/request/HttpRequestLine.java
- src/main/java/http/request/URI.java
- src/main/java/http/response/HttpResponse.java
- src/main/java/service/UserService.java
- src/main/java/service/UserServiceImpl.java
- src/main/java/utils/FileIoUtils.java
- src/main/java/utils/HttpRequestGenerator.java
- src/main/java/utils/StatusCode.java
- src/main/java/webserver/Dispatcher.java
- src/main/java/webserver/RequestHandler.java
- src/main/resources/templates/user/form.html
- src/test/java/request/HttpRequestBodyTest.java
- src/test/java/request/HttpRequestLineTest.java
- src/test/java/request/HttpRequestTest.java
- src/test/java/request/URITest.java
- 회원가입을 get을 통해 진행하던 것에서 post로 변경
- RequestBody를 Content-Length 헤더 값을 이용하여 받아오는 방식으로 변경
- UserLoginController를 추가하여 login 기능 구현
- Login 성공/실패 시 적절한 페이지로 redirect 하는 메서드 추가
- UserLoginController와 UserCreateController 테스트코드 작성
- User Password 암호화
- 회원가입 시 유효한 userId인지 확인하는 부분 추가
> [장민호] 웹서버 step4 구현

- README.md
- src/main/java/Controller/UserController.java
- src/main/java/exception/ControllerNotFoundException.java
- src/main/java/exception/NullValueException.java
- src/main/java/exception/UrlNotFoundException.java
- src/main/java/exception/UserValidationException.java
- src/main/java/http/request/HttpRequest.java
- src/main/java/http/response/HttpResponse.java
- src/main/java/service/UserService.java
- src/main/java/util/ControllerMapper.java
- src/main/java/util/HttpRequestUtils.java
- src/main/java/view/ViewResolver.java
- src/main/java/webserver/FrontController.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
- src/main/resources/templates/user/form.html
- src/main/resources/templates/user/form_failed.html
- src/test/java/kr/codesquad/util/HttpRequestUtilsTest.java
Step4 구현을 완료하였고, 저번주에 미처 하지 못했던 예외처리와 404 Not Found 응답을 보내는 기능을 구현하였다.
예외처리를 쉽게 하기 위해 `FrontController` 클래스를 생성하고, `RequestHandler`의 `run()` 메서드에서 `HttpRequest`, `HttpResponse` 객체 생성 후 수행하는 로직을 `FrontController`의 `process()` 메서드로 이동하였다.
매핑되는 컨트롤러가 없는 경우, 컨트롤러 내에서 매핑되는 URL이 없는 경우, `ViewResolver`를 통해 받은 파일 경로에 파일이 없는 경우 404 Not Found 응답을 보내도록 구현하였다.
또한 회원가입 시 발생한 예외를 처리하고 `/user/form_failed.html`로 리다이렉트 하는 기능을 구현하였다.
- `HttpRequest` 클래스 수정사항
1.  `FrontController`의 `process()` 메서드에서 `ControllerNotFoundException`, `UrlNotFoundException`, `FileNotFoundException `예외를 try-catch 문으로 잡아내어 예외가 발생할 경우  `httpResponse.notFound()` 메서드를 호출하여 404 Not Found 응답을 보내도록 함
2. 회원가입 시 아이디가 중복되었거나 입력 폼에 아무 값도 입력하지 않은 경우 발생하는 예외를 처리
> [임수민] 웹 서버 4단계 구현 완료 및 예외 처리

- src/main/java/webserver/Paths.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/SignUpController.java
- src/main/java/webserver/controller/Controller.java
- src/main/java/webserver/controller/ControllerMapper.java
- src/main/java/webserver/controller/SignUpController.java
- src/main/java/webserver/controller/StaticFileController.java
- src/main/java/webserver/httpUtils/Request.java
- src/main/java/webserver/httpUtils/RequestParser.java
- src/main/java/webserver/httpUtils/Response.java
- src/main/java/webserver/httpUtils/ResponseHandler.java
- src/main/resources/templates/user/form.html
- src/main/resources/templates/user/form_failed.html
- 컨트롤러 맵퍼를 통해 request에 따른 컨트롤러를 맵핑함으로써 다양한 요청에 대한 처리 기대.
------------------
- 회원가입 완료 후 redirect 부분을 http status code 302를 이용하도록 다시 구현
- build.gradle이 뭔가 꼬인 듯.. 단위테스트 모듈 다시 생성해보기
- postman을 통한 테스트
- 이후의 요구사항 구현
> [한상훈] step4 구현

- src/main/java/controller/AbstractController.java
- src/main/java/controller/FileController.java
- src/main/java/controller/RequestMappingHandler.java
- src/main/java/controller/UserController.java
- src/main/java/request/HttpRequest.java
- src/main/java/request/HttpRequestUtils.java
- src/main/java/webserver/RequestHandler.java
- src/test/java/webserver/HttpRequestUtilsTest.java
- webapp/400.html
- webapp/500.html
- webapp/user/form.html
- Content-Length가 헤더에 있을시 해당 길이만큼 입력을 받도록 처리
- HttpParser에서 파싱해서 requestBody HashMap에 저장
- 회원가입 후 리다이렉트 설정
- 정의되어있지 않은 메서드로 접근시 Bad Request 보내주도록 설정
- HttpParser의 책임 분리 (생성자 쪽에서 할지 고민)
- Controller 부분 확장하기 쉽게 리팩토링
- 테스트 코드 작성
> [유경민] step4 구현

- README.md
- src/main/java/Controller/Controller.java
- src/main/java/Controller/StaticResourceController.java
- src/main/java/Controller/UserController.java
- src/main/java/http/request/HttpRequest.java
- src/main/java/http/response/HttpResponse.java
- src/main/java/service/UserService.java
- src/main/java/util/ControllerMapper.java
- src/main/java/webserver/FrontController.java
- src/main/java/webserver/session/SessionManager.java
- src/main/resources/templates/user/form_failed.html
Step5 구현을 완료하였고, Step6 구현 중입니다. 또한 `Controller` 인터페이스를 변경하고 리팩토링을 진행하였습니다.
`Controller` 인터페이스의 `process()` 메서드 반환타입을 `String`에서 `void`로 변경하였습니다.
원래는 `Controller`의 `process()` 메서드의 반환타입을 `String`으로 정하여 응답에 사용할 뷰 파일 이름을 반환하도록 작성하였습니다. 이 때, 리다이렉트 응답인 경우 뷰 파일이 필요하지 않기 때문에 `Controller`의 `process()`가  "" 빈 문자열을 반환하도록 하였습니다. 하지만 실제 파일 경로를 통해 응답할 파일을 읽어오는 경우는 `StaticResourceController`만 수행하는 기능이기 때문에 인터페이스 메서드의 반환타입을 `void`로 변경하고, 응답에 보낼 파일을 읽어오는 기능은 `StaticResourceController`클래스의 `process()` 메서드가 수행하도록 수정하였습니다.
- `UserController`, `StaticResourceController`의 `process()` 메서드 반환타입을 `void`로 변경
- `StaticResourceController`의 `process()` 내부 로직 변경
- `ViewResolver.resolveViewName()`을 호출해 실제 파일 경로를 가져옴
- `Files.readAllBytes()`를 호출해 응답에 보낼 파일을 읽어옴
- 정상적으로 파일을 읽어오면 `response.ok()`, …
> [임수민] Step5 구현 완료 및 Step6 구현 중

- src/main/java/Utility/UserValidation.java
- src/main/java/controller/RequestController.java
- src/main/java/controller/StaticFileController.java
- src/main/java/controller/UserAccountController.java
- src/main/java/httpMock/CustomHttpFactory.java
- src/main/java/httpMock/CustomHttpRequest.java
- src/main/java/httpMock/CustomHttpResponse.java
- src/main/java/model/Session.java
- src/main/java/repository/SessionRepo.java
- src/main/java/service/SessionService.java
- src/main/java/service/StaticFileService.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/RequestRouter.java
- src/main/resources/templates/index.html
- src/main/resources/templates/user/form.html
- src/main/resources/templates/user/list.html
- src/main/resources/templates/user/login.html
- src/main/resources/templates/user/profile.html
- src/test/java/controller/UserAccountControllerTest.java
- src/test/java/model/SessionTest.java
- src/test/java/webserver/RequestRouterTest.java
- Session을 관리하기 위한 model, Repo, Service 클래스를 추가함
- 로그인 요청을 받고, 성공 여부에 따라 set-cookie를 통해 쿠키를 설정함.
- 로그인을 유지하고, 유저의 정보를 캐내기 위해서 session이 유지되어야 함.
- 로그인 요청을 받은 이후 로그인 됬다면 sid를 하나 만들고 그를 쿠키에 넣어줘야함.
- SessionRepo, SessionService 2개를 만들어서 각각의 controller가 필요한 로직을 service에 그중 공통 로직을 repo로 분리하려고 시도함.
> [노현욱] Week3 step2

- src/main/java/controller/UserController.java
- src/main/java/model/request/Request.java
- src/main/java/model/request/RequestBody.java
- src/main/java/model/session/Session.java
- src/main/java/model/session/Sessions.java
- src/main/java/service/UserService.java
- src/main/resources/templates/index.html
- src/main/resources/templates/user/form.html
- src/main/resources/templates/user/list.html
- src/main/resources/templates/user/login.html
- src/main/resources/templates/user/login_failed.html
- src/main/resources/templates/user/profile.html
- Session 객체 하나를 담당하는 Session class 생성
- 생성될 수 있는 여러 Session 객체들을 담당하는 Sessions class 생성
- 유저가 로그인에 성공하는 경우, cookie를 응답하고 Session을 생성하여 저장할 수 있도록 구현(Session에서 어떤 정보를 관리할지 고민 중)
- 유저 리스트를 확인하는 경우에 로그인이 되어 있는 경우와 되어 있지 않는 경우를 동적으로 처리해주기 위해 모든 HTML 파일에서 해당 버튼 클릭 시 /user/list.html이 아닌 /user/list를 요청하도록 수정
- 로그인되어 있지 않은 경우에 /user/list 요청 들어오면 login.html 페이지로 리다이렉트되도록 구현
- 현재 Session 객체에 userId 정보 하나만 갖고 있어서 어떤 정보를 추가로 관리할지 고민
- 3단계 미션 중 로그인되어 있는 경우, index.html과 /user/list 요청 시 동적으로 HTML 처리될 수 있도록 구현(미션 3단계 구현 완료)
- Session을 언제 만료시켜야 할지 고민(원종님이 알려주신 방식(Session 생성 시각을 저장하고, 만료 주기를 저장한 후에 요청이 날아 올 때마다 생성 시각과 비교하여 만료 주기를 지난 경우에는 Session을 만료시키고 다시 요청받을 수 있게) 좋은 것 같음👍)
- 쿠키 만료도 같이 고민
- 예외 처리 및 단위 테스트 작성
- README 정리 원래 오늘 하려고 했는데 실패... 할 일 빠르게 끝내고 할 예정
- 시간 남으면 Spring 공부 시작할 예정
> [박준수] 미션 2단계 쿠키를 이용한 로그인 구현 후 미션 3단계 중 로그인되어 있지 않은 경우만 처리

- README.md
- src/main/java/db/SessionStorage.java
- src/main/java/enums/UserEnum.java
- src/main/java/model/User.java
- src/main/java/service/UserService.java
- src/main/java/util/HttpParser.java
- src/main/java/util/Session.java
- src/main/java/was/controller/ControllerFactory.java
- src/main/java/was/controller/UserController.java
- src/main/java/was/dispatcher/PostDispatcher.java
- src/main/java/webserver/domain/HttpRequest.java
- src/main/java/webserver/domain/HttpResponse.java
- src/main/java/webserver/handler/ControllerHandlerFactory.java
- src/main/java/webserver/handler/QueryStringHandler.java
- src/main/java/webserver/session/Session.java
- src/test/java/db/SessionStorageTest.java
- src/test/java/service/UserServiceTest.java
- src/test/java/util/HttpParserTest.java
- src/test/java/util/SessionTest.java
1. 이전 코드 싱글턴으로 리팩터링
2. 쿠키와 세션 구현
1.
- Request객체와 Response 객체를 제외하고는 새롭게 생성될 이유가 없다고 판단.
- Controller와 Service는 Request에 담겨진 내용을 바탕으로 처리만 하면되므로 싱글턴으로 작성해도 된다고 판단.
1. 
- 내부에 정적 객체를 선언하고 정적 팩터리 메서드를 통해 정적 객체를 요청할때 초기화가 되어 있지 않으면 private 생성자를 이용해 초기화한 값을 리턴.
- 이미 초기화되어 객체가 담겨 있다면, 그 객체를 리턴하도록함.
2.
- 쿠키는 로그인 완료 후 response header에 Set-Cookie 헤더를 통해 전달 할 수 있게함.
- 쿠키는 sid=세션UUID; 로 값을 채웠다.
- path 설정을 안해주면 쿠키를 발급한 해당 url만 적용되었기 때문에, path=/ 해서 모든 경로에서 다 쿠키를 사용할 수 있도록 함
- Session을 관리하는 SessionStorage를 만들고 key = SID, value = Session 객체 를 map에 담아 메모리에서 관리.
1. 쿠키만료 timeout 설정
2. 세션 timeout 설정
4. 로그아웃
메모리에서 session을 관리하기 때문에 session의 크기를 최소화하는 것이 관건이고, 세션도 필요없을 때는 삭제되어야 한다고 판단.
세션의 만료타임을 측정하는 부분을 톰캣의 구현방식을 참고하려고함.
> [Cookie-Session] 박원종 쿠키세션 구현 중 제출합니다.

- src/main/java/controller/FileController.java
- src/main/java/controller/FrontController.java
- src/main/java/controller/LoginController.java
- src/main/java/controller/RequestMappingHandler.java
- src/main/java/controller/UserController.java
- src/main/java/cookie/Cookie.java
- src/main/java/db/UserReposioryImpl.java
- src/main/java/db/UserRepository.java
- src/main/java/model/User.java
- src/main/java/request/HttpRequest.java
- src/main/java/response/HttpResponse.java
- src/main/java/service/UserService.java
- src/main/java/session/Session.java
- src/main/java/session/SessionManager.java
- src/main/java/webserver/RequestHandler.java
- controller, service, repository로 역할 분리
- controller, service, repository, front controller 모두 싱글톤으로 리팩토링
- 어플리케이션 띄울 때 객체 생성하는 것이 아니라 첫 요청에서 생성됨 (lazy init)
- front controller 패턴 구현
- cookie, session 클래스 구현 및 적용 중
- post 로그인 redirect(success, fail)까지 구현 완료
- cookie, session 구현 마무리
- 테스트 코드 작성
- 리팩토링
- 동적 HTML
> [유경민] step5 구현중

- src/main/java/controller/ControllerHandler.java
- src/main/java/controller/DynamicController.java
- src/main/java/controller/StaticController.java
- src/main/java/controller/ViewController.java
- src/main/java/http/HttpSession.java
- src/main/java/http/SessionHandler.java
- src/main/java/http/request/HttpRequest.java
- src/main/java/http/request/HttpUri.java
- src/main/java/http/request/RequestLine.java
- src/main/java/http/request/ResourceType.java
- src/main/java/http/response/DynamicResolver.java
- src/main/java/http/response/HttpResponse.java
- src/main/java/http/response/HttpResponseFactory.java
- src/main/java/service/UserService.java
- src/main/java/util/FileIoUtil.java
- src/main/java/webserver/RequestHandler.java
- src/main/resources/templates/index.html
- src/main/resources/templates/qna/form.html
- src/main/resources/templates/qna/show.html
- src/main/resources/templates/user/form.html
- src/main/resources/templates/user/list.html
- src/main/resources/templates/user/login.html
- src/main/resources/templates/user/login_failed.html
- src/main/resources/templates/user/profile.html
- src/test/java/ControllerHandlerTest.java
- 사용자가 로그인 상태일 경우 /index.html에서 사용자 이름을 표시해 준다.
- 사용자가 로그인 상태가 아닐 경우 /index.html에서 [로그인] 버튼을 표시해 준다.
- 사용자가 로그인 상태일 경우 http://localhost:8080/user/list 에서 사용자 목록을 출력한다.
- http://localhost:8080/user/list  페이지 접근시 로그인하지 않은 상태일 경우 로그인 페이지(login.html)로 이동한다.
- 테스트 코드 작성
- 로그인 시 로그인 창으로 이동하지 못하도록 처리
- 리팩토링할 부분 있는지 생각해보기
> [김태완] Step6 기능 구현

- README.md
- src/main/java/Controller/DynamicResourceController.java
- src/main/java/Controller/HomeLoginController.java
- src/main/java/Controller/StaticResourceController.java
- src/main/java/Controller/UserController.java
- src/main/java/http/request/HttpRequest.java
- src/main/java/service/UserService.java
- src/main/java/util/ControllerMapper.java
- src/main/java/util/FileUtils.java
- src/main/java/view/HomeLoginView.java
- src/main/java/view/UserListView.java
- src/main/java/webserver/FrontController.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/session/Session.java
- src/main/java/webserver/session/SessionConst.java
- src/main/java/webserver/session/SessionManager.java
- src/main/resources/templates/index.html
- src/main/resources/templates/user/form.html
- src/main/resources/templates/user/form_failed.html
- src/main/resources/templates/user/list.html
- src/main/resources/templates/user/login.html
- src/main/resources/templates/user/login_failed.html
- src/main/resources/templates/user/profile.html
- src/test/java/kr/codesquad/util/HttpRequestUtilsTest.java
- src/test/java/kr/codesquad/view/ViewResolverTest.java
- src/test/java/kr/codesquad/webserver/session/SessionManagerTest.java
- src/test/java/kr/codesquad/webserver/session/SessionTest.java
Step6 구현을 완료하였고, Step5의 세션을 활용하여 로그인하는 기능을 수정했습니다.
1. http://localhost:8080/user/list  페이지 접근시 로그인하지 않은 상태일 경우 로그인 페이지(`login.html`)로 이동한다.
2.  사용자가 로그인 상태일 경우 http://localhost:8080/user/list 에서 사용자 목록을 출력한다.
3. 사용자가 로그인 상태일 경우 `/index.html`에서 사용자 이름을 표시해 준다.
---
Step6 기능을 수정하였고, 단위 테스트를 작성하였습니다.
- 로그인하지 않았으면 S`taticResourceController.process()` 호출
- 화면을 렌더링하기 위해 `HomeLoginView.render()`를 호출할 때 인자로 URL도 같이 넘겨주도록 변경
- `HomeLoginView`에서 html 파일 내용을 바꿀 때, `index.html`을 포함한 모든 html 파일에서 대체되는 부분을 통일하기 위해 변경
- `"user/login.html"` -> `"../user/login.html"`
- `"user/form.html"` -> `"../user/form.html"`
> [임수민] Step6 구현 완료

- src/main/java/controller/NotFoundController.java
- src/main/java/controller/UserController.java
- src/main/java/controller/ViewController.java
- src/main/java/model/request/Request.java
- src/main/java/model/request/RequestBody.java
- src/main/java/model/response/Response.java
- src/main/java/model/session/Session.java
- src/main/java/service/UserService.java
- src/main/java/util/ControllerMapper.java
- src/main/java/util/HeaderUtils.java
- src/main/resources/templates/index.html
- src/main/resources/templates/user/form.html
- src/main/resources/templates/user/list.html
- src/main/resources/templates/user/login.html
- src/main/resources/templates/user/login_failed.html
- src/main/resources/templates/user/profile.html
- src/test/java/model/request/RequestLineTest.java
- Session ID 가져 오는 로직이 일단 생성한 session ID로 응답 헤더 만든 다음 다시 헤더에서 파싱하는 이상한 순서로 구현되어 있어서 생성한 session ID는 그대로 사용하고 응답 헤더 만들 때 메서드의 인자값으로 담는 방식으로 재구현
- 응답 HTTP 메시지의 헤더 부분 만드는 메서드가 너무 많고 Controller마다 위치해 있어서 따로 HeaderUtils class 생성하여 모두 해당 클래스에서 관리
- 로그인되어 있는 경우 유저 리스트 확인하는 페이지 동적으로 생성하는 메서드 구현
- Request 메시지의 헤더에서 Cookie 읽을 때 해당 정보가 없는 경우 처리가 안 되어 있어 NPE 발생, 해당 부분 예외 처리
- 요청 넘어 올 때 문자 깨지는 부분 URLDecoder 사용해서 해결
- 로그인되어 있는 경우, 로그인 버튼 대신 로그인한 유저의 ID가 보일 수 있도록 구현
- 예외 처리
- 단위 테스트 작성
- 현재는 미션 기능 요구 사항만 딱 충족하도록 구현된 상태라서 좀 더 이해할 수 있는 흐름으로 동작하도록 구현(예를 들면, 현재는 로그인한 경우 로그인 텍스트가 유저 ID로 바뀌었는데도 불구하고 클릭하면 로그인 화면이 뜬다.)
- 쿠키랑 세션 만료되는 경우 어떻게 처리할지 고민
- 일부 예외 처리
- 유저가 로그인한 상태일 때 사용자 목록 확인하는 화면에서는 로그인 텍스트가 유저 이름으로 변경되지 않아서 수정
- 세션에서 String 데이터만 저장하고 있었는데, Object를 저장할 수 있도록 수정
- 로그인한 상태에서 유저 ID가 아닌 이름이 보이도록 수정
- 유저가 …
> [박준수] 미션 6단계 기능 요구 사항 구현까지 완료

- src/main/java/controller/ErrorController.java
- src/main/java/controller/FileController.java
- src/main/java/controller/FrontController.java
- src/main/java/controller/LoginController.java
- src/main/java/controller/RequestMappingHandler.java
- src/main/java/controller/UserController.java
- src/main/java/db/UserReposioryImpl.java
- src/main/java/exception/BadRequestException.java
- src/main/java/exception/HttpException.java
- src/main/java/exception/InternalServerErrorException.java
- src/main/java/exception/NotFoundException.java
- src/main/java/request/HttpRequest.java
- src/main/java/response/HttpResponse.java
- src/main/java/webserver/RequestHandler.java
- 세션 및 쿠키 구현
- request 관련 예외처리 추가
- ErrorController에서 받아서 에러 메시지를 클라이언트 쪽으로 내려주도록 구현
- JVM 이론 정리
- 쿠키와 세션 이론 정리
- 동적 페이지 생성
- 테스트 코드
- 예외처리
> [유경민] step5 구현 완료

- README.md
- build.gradle
- src/main/java/controller/ArticleController.java
- src/main/java/controller/Controller.java
- src/main/java/controller/ControllerSelector.java
- src/main/java/controller/DynamicController.java
- src/main/java/controller/DynamicRenderer.java
- src/main/java/controller/LoginController.java
- src/main/java/controller/StaticController.java
- src/main/java/controller/TemplateController.java
- src/main/java/controller/UserController.java
- src/main/java/db/BoardDatabase.java
- src/main/java/db/Database.java
- src/main/java/db/UserDatabase.java
- src/main/java/enums/ControllerTypeEnum.java
- src/main/java/model/Article.java
- src/main/java/response/ResponseStatusLine.java
- src/main/java/utils/StringBuilderUtils.java
- src/main/java/webserver/DatabaseConnHandler.java
- src/main/java/webserver/RequestResponseHandler.java
- src/main/resources/templates/index.html
- src/main/resources/templates/qna/form.html
- src/test/java/db/DatabaseTest.java
- src/test/java/webserver/DatabaseConnHandlerTest.java
[ 변경점 / 구현점 ]
7단계 구현을 완료하였습니다 . 
1. 구현을 위해 db 와 커넥션을 형성하는 기능 구현
2. 기존의 static file 로 관리하던 유저 데이터를 db 로 이전
3. 게시판 기능 구현을 위해 게시판 객체 생성, 해당 게시판을 관리 할 수 있는 boardDb 생성
4. 게시판 db 와 잘 연동. 
[ 개선해야 할 점 ]
1. 새로 생긴 todo 처리
2. 게시판 수에 따라 아래 index 들 처리해보기.
3. 로그아웃, 쿠키 리프레시 ( 내 편의를 위해, 서버 예외 처리를 위해)
[ 한마디 ]
기능 구현은 금방 처리가 되었는데, 예외 처리부분들이 아직 많이 부족한듯 합니다. 내일부터는 시간을 예외처리하는데 전부 쓰려고 합니다.
> [유준민 4주차 7단계 기능 구현] 

- build.gradle
- src/main/java/controller/Controller.java
- src/main/java/controller/Domain.java
- src/main/java/controller/FacadeController.java
- src/main/java/controller/MainController.java
- src/main/java/controller/PostController.java
- src/main/java/dao/PostDAO.java
- src/main/java/db/DBUtil.java
- src/main/java/db/Database.java
- src/main/java/dto/PostCreateDTO.java
- src/main/java/exception/DBException.java
- src/main/java/filesystem/FileSystem.java
- src/main/java/filesystem/HtmlGenerator.java
- src/main/java/filesystem/PathResolver.java
- src/main/java/model/Post.java
- src/main/java/repository/PostRepository.java
- src/main/java/service/AuthService.java
- src/main/java/service/PostService.java
- src/main/resources/templates/index.html
- src/main/resources/templates/qna/form.html
- src/main/resources/templates/qna/show.html
- src/test/java/mysql/ConnectionTest.java
1. Post와 관련한 클래스를 생성
- Post
- PostController
- PostService
- PostDTO
- ...
2. memory를 이용한 기능 구현
- 현재는 메모리를 통해 post 데이터를 다루도록 함
- MySQL + JDBC 연동은 완료한 상태
3. post authorization
- 로그인 여부에 따라 포스트 작성  기능을 제한함
4. dynamic html
1. MySQL + JDBC migration 계속
2. 리팩토링
3. 학습 정리
> [이원주] Step7 제출합니다

- .gitignore
- README.md
- build.gradle
- src/main/java/Utility/HtmlMakerUtility.java
- src/main/java/Utility/PostValidation.java
- src/main/java/controller/PostController.java
- src/main/java/controller/StaticFileController.java
- src/main/java/controller/UserAccountController.java
- src/main/java/model/Post.java
- src/main/java/model/User.java
- src/main/java/repository/DBConnectionManager.java
- src/main/java/repository/DBPostRepo.java
- src/main/java/repository/DBUserRepo.java
- src/main/java/repository/MemoryUserRepo.java
- src/main/java/repository/PostRepo.java
- src/main/java/repository/UserRepo.java
- src/main/java/service/PostService.java
- src/main/java/service/SessionService.java
- src/main/java/service/UserService.java
- src/main/java/webserver/RequestRouter.java
- src/main/resources/templates/index.html
- src/main/resources/templates/qna/form.html
- src/test/java/Repository/DBConnectionTest.java
- src/test/java/controller/UserAccountControllerTest.java
- src/test/java/webserver/RequestRouterTest.java
- post를 작성할수 있는 기능을 추가
- DB를 연결하며 기존의 memory 기반 repository들을 모두 DB 기반으로 수정. 혹은 Inteface화를 진행함.
- 요구사항이었습니다.
- 기존에 interface화 되어있지 않았던 class 들이 db를 연동하려고 보니 완전히 새로작성해야하는 경우가 발생했습니다. 그에따라서 interface class로 일단 만들어 두고, 해당 클래스를 db와 연동되는 repository 구현체를 이용해 구현할 수 있도록 하려고 합니다.
- post관련해서 동적 html 생성기능 추가, user의 인증 여부를 통해 새글 작성 화면을 보여주거나, 보여주지 않음
- 외부 DB를 연동시켜서 글들이 저장되도록 만들어두고, 회원가입 로직 등등도 Connection 객체를 통해서 관리할 수 있도록 만들어 둠
> [노현욱] week4 일일 리스트 구현

- build.gradle
- src/main/java/controller/FileController.java
- src/main/java/controller/FrontController.java
- src/main/java/controller/QnaController.java
- src/main/java/controller/QnaShowController.java
- src/main/java/db/DBConnection.java
- src/main/java/view/FormView.java
- src/main/java/view/IndexView.java
- src/main/java/view/QnaDetailView.java
- src/main/java/view/ViewHandler.java
- src/main/resources/templates/index.html
- src/main/resources/templates/qna/show.html
내가 한 것
---
* mysql 연결을 통해 db와의 연동이 가능하게 함
* try-catch문을 통해 해당 작업이 끝나면 자동으로 close 되게끔 함
*  QnA 폼에 대한 post 처리 구현
* MySQL의 timestamp를 통해 저장 시간을 저장하도록 함
* sql문에서 order by를 통해 최신순으로 정렬되게끔 하였음 
* http 메세지 바디를 파싱하여 폼의 데이터를 획득함
* PreparedStatement를 통해 DB 테이블 조회 및 추가하는 메서드 구현
* 로그인 여부에 상관 없이 현재 DB 테이블에 있는 글 목록들을 보여줌
* 로그인 여부에 따라 글쓰기 버튼을 보여주거나, 보여주지 않음
* QnA 상세 페이지 구현(댓글 및 수정 기능을 제외함)
* 인덱스 페이지의 글 목록에서 글을 누르면 해당 상세 페이지가 렌더링되도록 하였음
* 동적 파일을 반환함
* 해당 상세 페이지로 갈 때, 쿼리 파라미터로 해당 글의 pk값을 부여함
* 쿼리 파라미터를 파싱하여 테이블에서 해당되는 row를 조회하여 데이터를 가져와서 화면에 렌더링
내가 배운 것
---
* jdbc를 통해 db와 연결
* 평소 native query를 잘 쓰지 않아 그 중요성을 많이 잊은 거 같아 반성했다
* 상세 페이지를 구현하면서 쿼리 파라미터를 직접 동적 페이지에 적용함
더 고민해야 할 것, 해야 할 것
---
* 테스트 코드!!
* 로직 분리 및 리팩토링
> [신정아] Step7 한 줄 게시판 구현

- .gitignore
- build.gradle
- src/main/java/controller/IndexController.java
- src/main/java/controller/PostController.java
- src/main/java/db/ConfigReader.java
- src/main/java/db/QueryBuilder.java
- src/main/java/db/QueryBuilderFactory.java
- src/main/java/service/Post.java
- src/main/java/service/PostService.java
- src/main/java/view/IndexView.java
- src/main/java/view/PostFormView.java
- src/main/java/view/ViewHandler.java
- src/main/java/webserver/Dispatcher.java
- src/main/resources/templates/index.html
- src/main/resources/templates/qna/form.html
- src/test/java/controller/StaticResourceControllerTest.java
- src/test/java/db/ConfigReaderTest.java
- src/test/java/db/QueryBuilderFactoryTest.java
- src/test/java/db/QueryBuilderTest.java
- src/test/java/utils/ResourceUtilsTest.java
- src/test/resources/db_config.xml
- 기능 요구 사항에 필요한 쿼리를 만들어 처리해주는 QueryBuilder 작성
- 공통 부분을 따로 빼어 최종적으로 하나의 쿼리를 만들 수 있도록 설계
- 동시성 문제를 처리하기 위해 ConnectionPool을 생각하였으나 생각보다 구현 난이도가 높다고 판단.
- 따라서 QueryBuilder의 Lifecycle을 메서드 단위로 사용하고 AutoCloseable를 구현하여 리소스 처리 
- 기존 질문하기 페이지는 정적 리소스 응답 처리로 전용 컨트롤러 존재 X
- 하지만 요구 사항 변경에 따라 로그인 여부 체크 필요
- 따라서 `PostController`를 작성하고 `doGet`, `doPost`  구현
- 요청 데이터를 통한 게시글 저장 로직을 처리하는 `PostService` 작성
- 기존 `index.html`은 정적 응답으로만 사용되었음.
- 저장된 게시글에 따라 동적으로 페이지가 변경되기 때문에 이를 처리하는 `IndexController`와 `IndexView` 작성
- 게시글이 작성된 메인 페이지
- <img width="720" alt="image" src="https://user-images.githubusercontent.com/64524916/214528906-f6932a79-6f2d-431c-80fe-4eb9a6c354ba.png">
> [박솔찬] Step7 한 줄 게시판 구현

- build.gradle
- src/main/java/controller/BoardController.java
- src/main/java/controller/RequestMappingHandler.java
- src/main/java/controller/UserController.java
- src/main/java/controller/UserListController.java
- src/main/java/db/DBManager.java
- src/main/java/db/UserRepositoryMysql.java
- src/main/java/model/Board.java
- src/main/java/model/User.java
- src/main/java/repository/BoardRepository.java
- src/main/java/repository/BoardRepositoryMysql.java
- src/main/java/repository/DBManager.java
- src/main/java/repository/Database.java
- src/main/java/repository/UserReposioryImpl.java
- src/main/java/repository/UserRepository.java
- src/main/java/repository/UserRepositoryMysql.java
- src/main/java/request/HttpRequest.java
- src/main/java/response/HttpResponse.java
- src/main/java/service/BoardService.java
- src/main/java/service/UserService.java
- src/main/java/session/SessionManager.java
- webapp/index.html
- webapp/qna/form.html
- JDBC 이용한 repository 구현 (Board, User)
- 메모리 이용하던 기존 구현체들을 JDBC사용한 구현체로 교체
- Board Controller 게시글 등록 기능 구현
- VIew 부분 구현하기
- 테스트 코드
- 리팩토링
- 게시글 리스트, 상세보기 구현
> [유경민] Step7 구현중

- build.gradle
- src/main/java/controller/BoardController.java
- src/main/java/controller/HomeController.java
- src/main/java/db/BoardDataBase.java
- src/main/java/model/Board.java
- src/main/java/reader/fileReader/TemplatesFileReader.java
- src/main/java/reader/requestReader/RequestGetReader.java
- src/main/java/request/RequestDataType.java
- src/main/java/request/Url.java
- src/main/java/util/global/ConfigReader.java
- src/main/java/util/global/DBConnector.java
- src/main/java/view/BoardRender.java
- src/main/java/view/HomeRender.java
- src/main/java/webserver/RequestHandler.java
- src/main/resources/application.properties
- src/main/resources/templates/index.html
- src/main/resources/templates/qna/form.html
- src/main/resources/templates/qna/show.html
- src/test/java/db/BoardDataBaseTest.java
- src/test/java/request/RequestDataTypeTest.java
- src/test/java/util/global/ConfigReaderTest.java
- src/test/java/view/HomeRenderTest.java
- application.properties를 읽도록 ConfigReader 생성
- ConfigRedaer를 이용한 DBConnector 객체 생성 및 DB 연결
- Board객체와 DBConnector를 이용하여 findAll, insert 쿼리 연결
- /qna/form.html에서 글 등록 시 DB에 저장 완료
- /index.html에서 글 목록을 최근순으로 정렬하여 보여줌
- /qna/show/23과 같이 PathVariable을 적용
- 위의 경로로 접속시 제목과 content도 같이 보이게 적용
- PathVariable을 읽을 수 있도록 ReqeustGetReader 수정
> [김규민]웹 서버 7단계 - 한 줄 게시판 구현

- src/main/java/controller/ArticleController.java
- src/main/java/controller/DynamicRenderer.java
- src/main/java/controller/StaticController.java
- src/main/java/controller/TemplateController.java
- src/main/java/db/BoardDatabase.java
- src/main/java/db/UserDatabase.java
- src/main/java/request/Request.java
- src/main/java/session/HttpCookie.java
- src/main/java/session/HttpSessions.java
- src/main/java/utils/StringBuilderUtils.java
- src/main/java/webserver/DatabaseConnHandler.java
- src/main/java/webserver/RequestResponseHandler.java
- src/main/resources/templates/index.html
- src/main/resources/templates/user/list.html
- src/main/resources/templates/user/login.html
[ 변경점 / 구현점 ]
7단계 구현이후, 수정해야 할 사항들을 진행하였습니다.
1. 브라우저의 쿠키가 그대로 유지 될 경우( 서버가 갑자기 닫혔다가 열렸을 때) 세션 아이디의 유효를 체크하는 부분을 구현하였습니다.
2. 로그인 후 버튼이 제대로 삭제되지 않는 부분들을 처리하였습니다.
3. db 연동이 덜 된부분들을 처리하였습니다.
[ 개선해야 할 점 ]
1. 로그아웃 버튼을 활성화 해보려고 합니다.
[ 한마디 ]
오늘 쿠키처리를 하는데 조금 애를 먹었는데, 이미 잘 구현을 해두고 해메이고 있었습니다.... 뇌내 메모리가 부족한 느낌입니다
> [유준민 4주차 코드 수정] 

- src/main/java/Utility/HtmlMakerUtility.java
- src/main/java/controller/PostController.java
- src/main/java/controller/StaticFileController.java
- src/main/java/controller/UserAccountController.java
- src/main/java/model/Post.java
- src/main/java/model/User.java
- src/main/java/repository/DBConnectionManager.java
- src/main/java/repository/DBPostRepo.java
- src/main/java/repository/DBUserRepo.java
- src/main/java/repository/MemorySessionRepo.java
- src/main/java/repository/MemoryUserRepo.java
- src/main/java/repository/PostRepo.java
- src/main/java/repository/SessionRepo.java
- src/main/java/repository/UserRepo.java
- src/main/java/service/PostService.java
- src/main/java/service/SessionService.java
- src/main/java/service/StaticFileService.java
- src/main/java/service/UserService.java
- src/test/java/Repository/DBConnectionTest.java
- src/test/java/controller/UserAccountControllerTest.java
- src/test/java/webserver/RequestRouterTest.java
코드리뷰를 받은 사항들을 수정하고 리팩토링을 진행했습니다.
- singleton pattern 구현방법을 일원화 진행했습니다.
- 인터페이스가 구현체를 선택하도록 만들어 두었습니다.
- 불필요한 packing을 제거했습니다.
> [노현욱] week4 refactoring

- src/main/java/db/Database.java
- src/main/java/util/ResponseHtmlUtils.java
- src/main/resources/templates/index.html
- src/test/java/model/request/RequestLineTest.java
- 기존의 메모 내용만 보이던 메인 화면에서 메모 작성 시간과 메모 작성자까지 확인할 수 있도록 수정
- 페이지가 존재하지 않지만, HTML 파일에 하드 코딩되어 있던 부분 삭제
> [박준수] 미션 7단계 기능 보완

- src/main/java/controller/BoardController.java
- src/main/java/db/BoardDataBase.java
- src/main/java/reader/fileReader/TemplatesFileReader.java
- src/main/java/util/global/DBConnector.java
- src/main/java/view/BoardRender.java
- src/main/resources/templates/qna/show.html
- src/test/java/reader/fileReader/TemplatesFileReaderTest.java
- src/test/java/reader/requestReader/RequestGetReaderTest.java
- src/test/java/view/BoardRenderTest.java
- PathVariable 처리
- PathVariable을 통한 게시판 상세 조회
- PathVariable url 오류 수정
- Board의 PK로 Board객체 찾기
- Board 랜더링 기능 추가 
- Member 객체 DB연결
- 싱글톤 synchronized 추가
> [김규민]7단계 기능 보완

- src/main/java/controller/BoardController.java
- src/main/java/controller/HomeController.java
- src/main/java/controller/LoginController.java
- src/main/java/controller/RequestMappingHandler.java
- src/main/java/controller/UserListController.java
- src/main/java/model/Board.java
- src/main/java/repository/BoardRepositoryMysql.java
- src/main/java/service/BoardService.java
- src/main/java/view/HomeView.java
- src/main/java/view/Model.java
- src/main/java/view/UserListView.java
- src/main/java/view/View.java
- src/main/java/webserver/RequestHandler.java
- webapp/index.html
- webapp/qna/form.html
- webapp/qna/show.html
- webapp/user/form.html
- webapp/user/list.html
- webapp/user/login.html
- webapp/user/login_failed.html
- webapp/user/profile.html
- controller단에서 view 만들던 부분을 View 클래스를 따로 만들어서 책임 분리
- JDBC 사용해서 게시판 리스트 동적 HTML 구현 완료
- 로그인 여부 확인해서 menubar 동적으로 구현 완료
- 테스트 코드
- 꼼꼼한 예외처리
- 리팩토링
> [유경민] Step7 구현완료

- src/main/java/db/PostDatabase.java
- src/main/java/db/QueryExecutor.java
- src/main/java/db/SessionDatabase.java
- src/main/java/db/UserDatabase.java
- src/main/java/model/Post.java
- src/main/java/model/Session.java
- src/main/java/model/User.java
- src/main/java/request/HandlerEnum.java
- src/main/java/request/RequestHandler.java
- src/main/java/request/handlers/IndexHandler.java
- src/main/java/request/handlers/LoginFailedHandler.java
- src/main/java/request/handlers/LoginHandler.java
- src/main/java/request/handlers/LogoutHandler.java
- src/main/java/request/handlers/NoMatchHandler.java
- src/main/java/request/handlers/QnAHandler.java
- src/main/java/request/handlers/StaticFileHandler.java
- src/main/java/request/handlers/UserCreateHandler.java
- src/main/java/request/handlers/UserListHandler.java
- src/main/java/service/PostService.java
- src/main/java/service/SessionService.java
- src/main/java/service/UserService.java
- src/main/resources/templates/index.html
- src/main/resources/templates/qna/form.html
- src/main/resources/templates/qna/show.html
- src/main/resources/templates/user/create.html
- src/main/resources/templates/user/list.html
- src/main/resources/templates/user/login.html
- src/main/resources/templates/user/login_failed.html
- src/main/resources/templates/user/profile.html
- src/test/java/SessionTest.java
* 7단계 구현 완료
* 사용한 기술에 대해 좀 더 세부적 공부 및 동작 원리 파악
* 코드 개선(optional)
> [장덕진] 7단계 구현 완료
